# .streamlit/secrets.toml

TURSO_DB_URL = "libsql://mystocks-lakemind9.aws-ap-northeast-1.turso.io"
TURSO_AUTH_TOKEN = "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJhIjoicm8iLCJpYXQiOjE3Njk0OTQyMDIsImlkIjoiYjA1OTY4NWItM2MzMC00NTg0LWE0M2YtM2I4ZWUyOWMwYTcwIiwicmlkIjoiM2E2NzQwYmQtOTRiZS00NjNkLWE2ZWYtN2ZlOGUzZGY1NTBlIn0.yELDul2Z-4mQHIkhDCsTTxM5ONvjHB48jONHdZkg-NCXxsAg00qmrYlVYsDrlbE2WUqPLvbl9WYED3RMbxwmAQ"